"""
Silvermere world data.

This module converts the verified Silvermere ASCII-map parser output into a
stable data structure suitable for the Evennia builder.

NO DATABASE CHANGES ARE MADE HERE.
"""

from world.silvermere_parser import (
    load_lines,
    collect_main_rooms,
    remove_text_contamination,
    assign_room_ids,
    detect_exits,
)


ZONE_KEY = "silvermere"
ZONE_NAME = "Silvermere"


# ---------------------------------------------------------------------------
# Confirmed / identified locations
# ---------------------------------------------------------------------------
#
# These use the permanent source-map room IDs generated by silvermere_parser.
#
# Do not change these IDs when room names or descriptions are edited later.
#

ROOM_OVERRIDES = {
    # ---------------------------------------------------------------
    # Central Silvermere
    # ---------------------------------------------------------------
    "silvermere_town_square": {
        "name": "Town Square",
        "description": (
            "The dark heart of Silvermere opens around you. Guild Street runs "
            "north and south while Blood Way cuts east and west through the "
            "square. A heavy iron manhole cover is set into the street."
        ),
        "street": "Guild Street / Blood Way",
        "tags": [
            "silvermere",
            "town_square",
            "evil_start",
            "manhole",
        ],
    },

    # ---------------------------------------------------------------
    # Armor district
    #
    # Town Square:
    #   north, west       = head / feet armor
    #   north, west, west = body / leg armor
    #   north from there  = shields
    # ---------------------------------------------------------------
    "silvermere_l70_c41": {
        "name": "The Iron Skull",
        "description": (
            "Helms, boots, greaves, and other protective gear line the walls "
            "of this grim armor shop."
        ),
        "street": "Blood Way",
        "tags": [
            "silvermere",
            "shop",
            "armor_shop",
            "head_foot_armor",
        ],
        "npc": "Varek Skullbinder",
    },

    "silvermere_l70_c37": {
        "name": "The Blackened Plate",
        "description": (
            "Dark suits of armor and heavy protective pieces crowd racks and "
            "stands throughout this forge-scarred shop."
        ),
        "tags": [
            "silvermere",
            "shop",
            "armor_shop",
            "body_armor",
        ],
        "npc": "Mordren Blacksteel",
    },

    "silvermere_l60_c37": {
        "name": "The Broken Aegis",
        "description": (
            "Shields of many shapes and sizes hang from reinforced walls, "
            "their battered surfaces catching the dim light."
        ),
        "tags": [
            "silvermere",
            "shop",
            "shield_shop",
        ],
        "npc": "Kharvek Grimward",
    },

    # ---------------------------------------------------------------
    # Bank
    #
    # Town Square: south, west
    # ---------------------------------------------------------------
    "silvermere_l74_c41": {
        "name": "The Black Iron Bank",
        "description": (
            "Heavy counters, iron fittings, and guarded storage doors give "
            "Silvermere's bank the appearance of a small fortress."
        ),
        "tags": [
            "silvermere",
            "bank",
            "shop",
        ],
    },

    # ---------------------------------------------------------------
    # Quest giver
    #
    # Town Square: south, east
    # ---------------------------------------------------------------
    "silvermere_l74_c49": {
        "name": "The Hall of Dark Endeavors",
        "description": (
            "Notices, contracts, rumors, and dangerous assignments fill this "
            "shadowed hall where Silvermere's adventurers seek work."
        ),
        "tags": [
            "silvermere",
            "quest_hall",
            "quest_giver",
        ],
        "npc": "Veyra Nightwhisper",
    },

    # ---------------------------------------------------------------
    # General/adventuring supplies
    #
    # This is the shop immediately south of the eastern Blood Way
    # commercial stretch identified from the original map.
    # ---------------------------------------------------------------
    "silvermere_l74_c57": {
        "name": "The Grim Provisioner",
        "description": (
            "Lanterns, torches, rope, packs, and other adventuring necessities "
            "fill shelves and hooks throughout this cramped general store."
        ),
        "tags": [
            "silvermere",
            "shop",
            "general_store",
            "adventuring_supplies",
        ],
        "npc": "Drevik Blackhand",
    },

    # ---------------------------------------------------------------
    # Western temple / death return area
    # ---------------------------------------------------------------
    "silvermere_l72_c9": {
        "name": "Sanctum of the Returned",
        "description": (
            "A cold sacred chamber lies beneath the shadow of Silvermere's "
            "temple complex. Dark rites performed here call fallen souls back "
            "from death."
        ),
        "street": "Black Veil Way",
        "tags": [
            "silvermere",
            "temple",
            "healer",
            "evil_death_return",
        ],
        "npc": "Malvek the Soulbinder",
    },
}


# ---------------------------------------------------------------------------
# Street names
# ---------------------------------------------------------------------------

STREET_NAMES = {
    "guild_street": "Guild Street",
    "blood_way": "Blood Way",
    "blacksteel_row": "Blacksteel Row",
    "executioners_way": "Executioner's Way",
    "graveborn_lane": "Graveborn Lane",
    "dreadmarch_road": "Dreadmarch Road",
    "shadow_alley": "Shadow Alley",
    "viper_lane": "Viper Lane",
    "ashen_way": "Ashen Way",
    "nightfall_row": "Nightfall Row",
    "bone_street": "Bone Street",
    "ravens_walk": "Raven's Walk",
    "hangmans_row": "Hangman's Row",
    "doomgate_road": "Doomgate Road",
    "black_veil_way": "Black Veil Way",
}


def build_silvermere_dataset():
    """
    Build and return the verified Silvermere room dataset.

    This calls the ASCII parser but does NOT interact with Evennia.
    """

    lines = load_lines()

    rooms = collect_main_rooms(lines)
    rooms = remove_text_contamination(rooms)
    rooms = assign_room_ids(rooms)
    rooms = detect_exits(lines, rooms)

    dataset = {}

    for room in rooms:
        room_id = room["room_id"]

        data = {
            "room_id": room_id,
            "zone": ZONE_KEY,
            "zone_name": ZONE_NAME,
            "symbol": room["symbol"],
            "source_line": room["source_line"],
            "source_col": room["source_col"],
            "name": room.get("name"),
            "description": None,
            "street": None,
            "tags": ["silvermere"],
            "npc": None,
            "exits": dict(room.get("exits", {})),
        }

        override = ROOM_OVERRIDES.get(room_id)

        if override:
            for key, value in override.items():
                if key == "tags":
                    existing = set(data["tags"])
                    existing.update(value)
                    data["tags"] = sorted(existing)
                else:
                    data[key] = value

        # Temporary neutral name for unidentified rooms.
        # These can be replaced with proper street/location names later
        # without changing the permanent room_id.
        if not data["name"]:
            data["name"] = (
                f"Silvermere "
                f"({data['source_line']}, {data['source_col']})"
            )

        if not data["description"]:
            data["description"] = (
                "You are somewhere within the dark streets and structures "
                "of Silvermere."
            )

        dataset[room_id] = data

    return dataset


def validate_dataset(dataset):
    """
    Validate the data before any Evennia builder is allowed to use it.
    """

    errors = []

    if len(dataset) != 285:
        errors.append(
            f"Expected 285 Silvermere rooms, found {len(dataset)}."
        )

    town_square = dataset.get("silvermere_town_square")

    if not town_square:
        errors.append("Town Square is missing.")
    else:
        expected = {
            "north": "silvermere_l70_c45",
            "south": "silvermere_l74_c45",
            "east": "silvermere_l72_c48",
            "west": "silvermere_l72_c41",
        }

        if town_square["exits"] != expected:
            errors.append(
                "Town Square exits do not match the verified map."
            )

    # Every exit destination must exist.
    for room_id, room in dataset.items():
        for direction, destination in room["exits"].items():
            if destination not in dataset:
                errors.append(
                    f"{room_id}: {direction} points to missing "
                    f"room {destination}"
                )

    # Every normal directional connection must have its reverse.
    opposite = {
        "north": "south",
        "south": "north",
        "east": "west",
        "west": "east",
    }

    for room_id, room in dataset.items():
        for direction, destination_id in room["exits"].items():
            destination = dataset[destination_id]
            reverse = opposite[direction]

            if destination["exits"].get(reverse) != room_id:
                errors.append(
                    f"{room_id} -> {direction} -> {destination_id} "
                    f"has no matching {reverse} exit."
                )

    return errors


def print_named_locations(dataset):
    print()
    print("Named Silvermere locations")
    print("=" * 72)

    for room_id, data in dataset.items():
        if room_id in ROOM_OVERRIDES:
            print(
                f"{room_id:<24} "
                f"{data['name']}"
            )


def main():
    dataset = build_silvermere_dataset()
    errors = validate_dataset(dataset)

    print()
    print("Silvermere data validation")
    print("=" * 72)
    print(f"Rooms: {len(dataset)}")
    print(f"Named locations: {len(ROOM_OVERRIDES)}")

    if errors:
        print()
        print(f"FAIL: {len(errors)} error(s)")
        for error in errors:
            print(f"  - {error}")
    else:
        print()
        print("PASS: Silvermere dataset validated.")

    print_named_locations(dataset)

    print()
    print("DATA ONLY")
    print("No Evennia database objects were created or modified.")


if __name__ == "__main__":
    main()
